name: my_tasks
version: 1.0.0
description: >
  یک پکیج محلی برای مدیریت وظایف در پروژه‌های فلاتر من.
  این پکیج شامل مدل‌ها و ویجت‌های مشترک مربوط به تسک‌ها است.
authors:
  - AminPourabazari <abzery.ap@example.com>
homepage:
repository:
issue_tracker:
documentation:
dependencies:
  flutter: 
    sdk: flutter
  url_launcher: any 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any 
  
environment:
  sdk: '>=3.0.0'

flutter:
